export const COLORS = {
  pastelCalm: {
    mintGreen: {
      primary: "#A8E6CF",
      text: "#13121aff",
      darker: "#6FC8A7",
      background: "#E6F9F2",
      onPrimary: "#FFFFFF",
      border: "#C8EDE0",
      surface: "#FFFFFF",
      backgroundGradient: "linear-gradient(135deg, #A8E6CF, #6FC8A7, #E6F9F2)",
    },
    babyBlue: {
      primary: "#DCEFFF",
      text: "#1A1A1A",
      darker: "#9CCCF2",
      background: "#F2F9FF",
      onPrimary: "#1A1A1A",
      border: "#C7E2FA",
      surface: "#FFFFFF",
      backgroundGradient: "linear-gradient(135deg, #DCEFFF, #9CCCF2, #F2F9FF)",
    },
    lavender: {
      primary: "#EADCF8",
      text: "#1A1A1A",
      darker: "#C2A8E6",
      background: "#F7F2FB",
      onPrimary: "#1A1A1A",
      border: "#DDC8F2",
      surface: "#FFFFFF",
      backgroundGradient: "linear-gradient(135deg, #EADCF8, #C2A8E6, #F7F2FB)",
    },
    peach: {
      primary: "#FFD3B6",
      text: "#1A1A1A",
      darker: "#F9A87B",
      background: "#FFF3EB",
      onPrimary: "#1A1A1A",
      border: "#F9CBB0",
      surface: "#FFFFFF",
      backgroundGradient: "linear-gradient(135deg, #FFD3B6, #F9A87B, #FFF3EB)",
    },
    lightGray: {
      primary: "#F6F6F6",
      text: "#1A1A1A",
      darker: "#CCCCCC",
      background: "#FFFFFF",
      onPrimary: "#1A1A1A",
      border: "#E0E0E0",
      surface: "#FFFFFF",
      backgroundGradient: "linear-gradient(135deg, #F6F6F6, #CCCCCC, #FFFFFF)",
    },
  },
  warmFriendly: {
    softYellow: {
      primary: "#FFF3B0",
      text: "#1A1A1A",
      darker: "#E6C94D",
      background: "#FFFAE0",
      onPrimary: "#1A1A1A",
      border: "#F5E7A2",
      surface: "#FFFFFF",
      backgroundGradient: "linear-gradient(135deg, #FFF3B0, #E6C94D, #FFFAE0)",
    },
    blushPink: {
      primary: "#F7C5CC",
      text: "#1A1A1A",
      darker: "#E68B97",
      background: "#FDECEF",
      onPrimary: "#1A1A1A",
      border: "#F2B7C0",
      surface: "#FFFFFF",
      backgroundGradient: "linear-gradient(135deg, #F7C5CC, #E68B97, #FDECEF)",
    },
    skyBlue: {
      primary: "#B5EAEA",
      text: "#1A1A1A",
      darker: "#6CCCCC",
      background: "#E9FDFD",
      onPrimary: "#1A1A1A",
      border: "#A0DCDC",
      surface: "#FFFFFF",
      backgroundGradient: "linear-gradient(135deg, #B5EAEA, #6CCCCC, #E9FDFD)",
    },
    lightCoral: {
      primary: "#FFBBB5",
      text: "#1A1A1A",
      darker: "#E67C72",
      background: "#FFE9E7",
      onPrimary: "#1A1A1A",
      border: "#F5AFA9",
      surface: "#FFFFFF",
      backgroundGradient: "linear-gradient(135deg, #FFBBB5, #E67C72, #FFE9E7)",
    },
    creamWhite: {
      primary: "#FEFAE0",
      text: "#1A1A1A",
      darker: "#E6DDA6",
      background: "#FFFFF8",
      onPrimary: "#1A1A1A",
      border: "#F2EBC8",
      surface: "#FFFFFF",
      backgroundGradient: "linear-gradient(135deg, #FEFAE0, #E6DDA6, #FFFFF8)",
    },
  },
  minimalRelaxed: {
    softTeal: {
      primary: "#A7D6D0",
      text: "#1A1A1A",
      darker: "#6BAFA5",
      background: "#E6F6F4",
      onPrimary: "#1A1A1A",
      border: "#95C9C2",
      surface: "#FFFFFF",
      backgroundGradient: "linear-gradient(135deg, #A7D6D0, #6BAFA5, #E6F6F4)",
    },
    coolGray: {
      primary: "#ECEFF1",
      text: "#1A1A1A",
      darker: "#B0BEC5",
      background: "#F9FAFB",
      onPrimary: "#1A1A1A",
      border: "#D9DEE2",
      surface: "#FFFFFF",
      backgroundGradient: "linear-gradient(135deg, #ECEFF1, #B0BEC5, #F9FAFB)",
    },
    powderBlue: {
      primary: "#C5CAE9",
      text: "#1A1A1A",
      darker: "#7986CB",
      background: "#EEF0F9",
      onPrimary: "#1A1A1A",
      border: "#B3B9E0",
      surface: "#FFFFFF",
      backgroundGradient: "linear-gradient(135deg, #C5CAE9, #7986CB, #EEF0F9)",
    },
    mutedLilac: {
      primary: "#D7CCC8",
      text: "#1A1A1A",
      darker: "#8D6E63",
      background: "#F3EEED",
      onPrimary: "#1A1A1A",
      border: "#C8BDB9",
      surface: "#FFFFFF",
      backgroundGradient: "linear-gradient(135deg, #D7CCC8, #8D6E63, #F3EEED)",
    },
    offWhite: {
      primary: "#FAFAFA",
      text: "#1A1A1A",
      darker: "#BDBDBD",
      background: "#FFFFFF",
      onPrimary: "#1A1A1A",
      border: "#E0E0E0",
      surface: "#FFFFFF",
      backgroundGradient: "linear-gradient(135deg, #FAFAFA, #BDBDBD, #FFFFFF)",
    },
  },
};
